export const REGIONS = [
  {n:'I', name:'Arousal & Sensory Processing', color:'#AC6120', soft:'#F3E5CB', desc:"The body's baseline: how much movement, stimulation, rhythm, and sensory detail the system runs on."},
  {n:'II', name:'Approach, Reward & Connection', color:'#66743A', soft:'#E4EAD4', desc:'The pull toward the world: novelty, pleasure, and the warmth of other people.'},
  {n:'III', name:'Threat, Frustration & Loss', color:'#7A4256', soft:'#E9DEE8', desc:'The protective systems: three distinct alarms for danger, for blocked goals, and for loss.'},
  {n:'IV', name:'Attention & Intentional Regulation', color:'#33686B', soft:'#D8E7E6', desc:'The steering wheel: what captures attention, and how well it can be placed, held, and redirected.'}
];

export const DIMS = [
{id:'engine', n:'01', name:'Motor Activity', trait:'Motor Activity', region:0, color:'#B4641F',
 poles:['Still and deliberate','Ceaseless motion'],
 metaphor:{name:'The Running River', text:'A river does not decide to move; motion is its nature. The high-activity body is water that must run, thinking and speaking and solving while in flow. Dammed too long, it does not grow calm. It grows pressured.'},
 cq:'Can my body move the way it needs to move here?',
 desc:'How much movement and physical engagement the body seeks simply to feel right. This is not energy as enthusiasm, and not athletic skill. It is the baseline appetite for motion.',
 high:['Moves frequently and spontaneously','Thinks and communicates while in motion','Grows restless in prolonged stillness','Engages the world physically, hands first'],
 low:['Moves deliberately, comfortable being still','Does careful work in quiet, low-movement settings','May tire during sustained physical activity','Watches and considers before acting'],
 gifts:[{t:'Momentum',d:'Energy, initiative, and a bias toward doing that moves a room from talk to action.'},{t:'Embodied thinking',d:'Ideas come loose when the body is in motion; many high-activity minds solve hard problems on their feet.'},{t:'Composure in stillness',d:'The low-activity person offers a calm, settled presence and long, patient, seated focus.'},{t:'Deliberateness',d:'Movement that is chosen rather than constant tends to be purposeful and precise.'}],
 edges:[{t:'Restlessness read as defiance',d:'The high-activity person is corrected for a bodily need, and learns shame rather than skill.'},{t:'Difficulty with enforced stillness',d:'Long meetings and lessons cost the active body more than others realize.'},{t:'Depletion mistaken for reluctance',d:"The low-activity person's fatigue in active settings can look like a lack of will."}],
 confuse:['impulsivity','distractibility','ADHD','athletic ability','enthusiasm','motivation'],
 fit:'Build legitimate movement into the day. Do not use stillness as the measure of engagement.',
 scaffold:'Plan movement before long still stretches. Wiggle, then work. Offer standing and walking options.',
 stretch:"Practice one chosen stillness a day, organized around the room's real needs, never imposed as punishment.",
 formation:"Formation here is not learning to sit down. It is learning to aim its motion. Energy without direction exhausts everyone, itself included. Energy yoked to purpose becomes one of the most generative forces a community can hold.",
 virtue:'Diligence, ordered energy', verse:'Whatever your hand finds to do, do it with your might. (Ecclesiastes 9:10)',
 concert:[{w:'Behavioral Regulation',t:'High motion with developing regulation is a body ahead of its brakes. Grow the brakes; do not dampen the motion.'},{w:'Attentional Capture',t:'High movement plus high capture reads as chaos, and is often simply a system built for input, needing structure rather than correction.'}]},

{id:'dynamo', n:'02', name:'Stimulation Need', trait:'Stimulation Need', region:0, color:'#A64E1B',
 poles:['Calm and steady','Hungry for intensity'],
 metaphor:{name:'The Furnace', text:'A furnace runs bright only when it is well fed. Starve the intensity-seeker of stimulation and it does not idle quietly; it hunts for fuel, stirring up excitement, risk, or friction to raise the heat. Give the calm-natured too much and it is not thrilled but overrun.'},
 cq:'Is there enough here to keep me lit?',
 desc:'How much novelty, speed, complexity, and intensity a person needs simply to feel awake and engaged. This is appetite, not detection.',
 high:['Seeks novelty, variety, and pace','Bored quickly by repetition','Adds stimulation when under-engaged','Comes alive in fast-moving settings'],
 low:['Content with calm and predictability','Prefers familiar, low-complexity settings','Can be overwhelmed by high intensity','Needs recovery after sustained stimulation'],
 gifts:[{t:'Drive and range',d:'Appetite for challenge, tolerance for chaos, and a gift for keeping energy up when others flag.'},{t:'Creative restlessness',d:'The search for the new often produces genuine novelty, invention, and momentum.'},{t:'Deep steadiness',d:'The calm-natured person offers calm endurance and thrives in patient, repetitive work others cannot bear.'},{t:'Contentment',d:'Less need for intensity means more capacity for stillness, focus, and peace.'}],
 edges:[{t:'Manufactured drama',d:'Under-stimulated, the intensity-seeker may create friction or risk simply to feel awake.'},{t:'Follow-through in the flat stretches',d:'The long, unglamorous middle of any project is the hardest ground for the intensity-seeker.'},{t:'Overwhelm read as fragility',d:"The calm-natured person's need to step out of intense settings can be misjudged as weakness."}],
 confuse:['sensory sensitivity','novelty approach','impulsivity','extroversion','courage'],
 fit:'Calibrate stimulation rather than maximizing or minimizing it. Build strategic novelty into repetitive work; guard quiet recovery for the calm-natured.',
 scaffold:'Teach the intensity-seeker to name under-arousal and choose good fuel. Give the calm-natured a way out of intensity before overload, not after.',
 stretch:'For the intensity-seeker, stay engaged when the pace is slower than preferred. For the calm-natured, stay organized when it is faster.',
 formation:"The fire itself is not the problem; misdirected fire is. Formation teaches the intensity-seeker to feed the furnace with work worth doing rather than drama, and teaches the calm-natured that their steadiness is not smallness but a rare and needed strength.",
 virtue:'Temperance, zeal rightly aimed', verse:'Never be lacking in zeal, but keep your spiritual fervor. (Romans 12:11)',
 concert:[{w:'Novelty & Reward Approach',t:'High stimulation need plus high approach seeks the edge of experience. Thrilling, and in need of a governor.'},{w:'Sensory Sensitivity',t:'A person can crave intensity and be overwhelmed by it at once, wanting the loud room and paying for it after. Name both.'}]},

{id:'metronome', n:'03', name:'Biological Rhythmicity', trait:'Biological Rhythmicity', region:0, color:'#C79A31',
 poles:['Improvised rhythms','Clockwork regularity'],
 metaphor:{name:'The Tide', text:'Some bodies keep tides you can set a calendar by, arriving and receding on schedule. Others run on weather, not clockwork. Neither is more virtuous. One is easier to plan around; the other bends more easily to the unexpected.'},
 cq:'Can I trust my body to keep its own time?',
 desc:"How predictable the body's own cycles are: sleep and waking, hunger and fullness, energy's rise and fall. Rhythmicity is not about discipline. It is about how regularly the body keeps its own time.",
 high:['Sleep, hunger, and energy arrive on schedule','Routines are easy to establish','Schedule disruption is strongly felt','Predictable, plannable days'],
 low:['Cycles vary from day to day','Fixed routines are hard to keep','Bodily needs require active monitoring','Adapts readily to change and irregular demands'],
 gifts:[{t:'Reliability',d:"The clockwork-regular body is a dependable partner; routines, once set, largely run themselves."},{t:'Early warning',d:'Because disruption registers strongly, the clockwork-regular person notices when something is off.'},{t:'Flexibility',d:'The irregular-rhythm person bends to travel, shift work, and the unexpected with less cost.'},{t:'Improvisation',d:'Living without fixed rhythm builds a real capacity to function when plans dissolve.'}],
 edges:[{t:'Rigidity under disruption',d:'The clockwork-regular person can struggle badly when the schedule breaks.'},{t:'Missed signals',d:'The irregular-rhythm person may not notice hunger or fatigue until it is extreme.'},{t:'Regularity mistaken for virtue',d:'Punctual bodies are not more disciplined; irregular ones are not more free.'}],
 confuse:['discipline','laziness','flexibility','willpower'],
 fit:'Track the actual pattern rather than assuming one. Use consistent cues; build buffers around change.',
 scaffold:'Help the irregular-rhythm person notice internal signals and externalize a rhythm. Prepare the clockwork-regular for coming disruption.',
 stretch:'Build reliable self-care that respects the real body while still meeting responsibilities.',
 formation:'The lesson here is that rhythm is a servant, not a master. The regular body offers its steadiness without demanding the world match it; the irregular body builds enough structure to keep its promises.',
 virtue:'Faithfulness, stewardship of the body', verse:'For everything there is a season, and a time for every matter under heaven. (Ecclesiastes 3:1)',
 concert:[{w:'Motor Activity',t:'Regular rhythm plus high motion thrives on a predictable active routine, and struggles when both are denied.'},{w:'Behavioral Regulation',t:"Low rhythmicity leans hard on regulation; external structure does the work the body's clock does not."}]},

{id:'attuned', n:'04', name:'Sensory Sensitivity', trait:'Sensory Sensitivity', region:0, color:'#8F6B21',
 poles:['Needs strong input','Notices everything'],
 metaphor:{name:'The Seismograph', text:'A seismograph registers tremors the body would otherwise miss. That sensitivity is a gift of perception and a cost of overload in equal measure. The instrument that feels the faintest signal is also the one most easily swamped by a loud one.'},
 cq:'Is the input here more than I can hold right now?',
 desc:"How readily a person detects faint sensory, bodily, and relational signals: a sound, a texture, a shift in a room's mood, the first flicker of hunger or fatigue. The highly sensitive live with the volume of the world turned up.",
 high:['Detects low-intensity input others miss','Notices subtle change and mood','Reaches overload more quickly','Registers bodily discomfort early'],
 low:['Needs stronger input to notice','Tolerates intense environments well','May overlook fatigue, injury, or subtle cues','Unbothered where others are overwhelmed'],
 gifts:[{t:'Perception',d:'The highly sensitive person catches what others miss: the wrong note, the falling face, the early warning.'},{t:'Depth of experience',d:'Beauty, music, flavor, and nuance land more richly on a sensitive system.'},{t:'Endurance in intensity',d:'The low-sensitivity person keeps working where others are swamped by noise and chaos.'},{t:'Attunement to others',d:'High social-perceptual sensitivity can read a room with unusual accuracy.'}],
 edges:[{t:'Overload read as drama',d:"The sensitive person's recoil from too much input is a real limit, not a performance."},{t:'Depletion after intensity',d:'A loud, bright, crowded day costs the sensitive more than it costs most.'},{t:'Missed cues',d:"The low-sensitivity person may overlook their own fatigue or another's distress."}],
 confuse:['creativity','empathy','anxiety','artistic ability','conscientiousness'],
 fit:'Name the specific channel. Reduce unnecessary sensory load; guard recovery after intense input.',
 scaffold:'Offer tools, a quiet corner, headphones, dim light, as supports rather than punishments.',
 stretch:'Widen the tolerable range gradually, and learn to tell discomfort from danger. For low sensitivity, practice checking bodily and relational cues.',
 formation:'The highly sensitive learn that sensitivity is not weakness to hide but a perception to steward, protected when it overloads, spent when it can serve. And the less sensitive learn to slow down and look twice, choosing to notice what does not announce itself.',
 virtue:'Attentiveness, reverent wonder', verse:'I am fearfully and wonderfully made; your works are wonderful. (Psalm 139:14)',
 concert:[{w:'Sadness & Loss Sensitivity',t:'High sensitivity feeding high sadness produces someone who feels the world deeply and needs help carrying it without drowning.'},{w:'Attentional Capture',t:'When sensitivity meets high capture, complex settings overwhelm fast. The fix is a calmer environment, not a sterner correction.'}]},

{id:'pioneer', n:'05', name:'Novelty & Reward Approach', trait:'Novelty & Reward Approach', region:1, color:'#4E7444',
 poles:['Watches first','Steps through the door'],
 metaphor:{name:'The Open Door', text:'To the quick approacher, an open door is an invitation the body answers before caution finishes speaking. To the low approacher, the same door is a question to study first. Both are wise in their way; each needs a measure of the other.'},
 cq:'What might be on the other side, and can I go and see?',
 desc:'How readily a person moves toward the unfamiliar, the interesting, or the potentially rewarding. Where others gather information at the edge, the quick approacher learns by walking in. Approach is not courage and not sociability.',
 high:['Enters new situations quickly','Feels opportunity as energizing','Learns by direct engagement','May act before finishing the risk assessment'],
 low:['Observes before entering','Wants information or familiarity first','Learns by watching and preparing','May delay despite real interest'],
 gifts:[{t:'Initiative',d:'The quick approacher starts things, tries things, and opens doors others would leave closed.'},{t:'Learning by doing',d:'Direct engagement teaches the quick approacher quickly and firsthand.'},{t:'Prudence',d:'The low approacher brings the gift of looking before leaping, and catching what haste would miss.'},{t:'Considered commitment',d:'Slower entry often means steadier, better-informed follow-through.'}],
 edges:[{t:'Leaping before looking',d:'High approach with low caution can walk into avoidable trouble.'},{t:'Restless with deliberation',d:"The quick approacher can experience others' caution as an obstacle."},{t:'Missed opportunity',d:'The low approacher can wait for a certainty that never comes and let the moment pass.'}],
 confuse:['affiliation','courage','adaptability','impulsivity','openness to ideas'],
 fit:'Give the quick approacher room to explore and try; give the cautious a preview and a graduated entry.',
 scaffold:"Pair the leap with a two-second scan. Let the cautious watch before joining, without forcing it.",
 stretch:'For high approach, name one consequence before acting. For low approach, enter one manageable uncertainty without waiting for full comfort.',
 formation:"Formation here is not learning to fear the door. It is learning to glance before crossing it. Boldness is a gift the world needs; boldness that has learned to ask one good question before it moves becomes leadership.",
 virtue:'Courage tempered by prudence', verse:'Be strong and courageous; do not be afraid. (Joshua 1:9), held with counsel: plans succeed with many advisers. (Proverbs 15:22)',
 concert:[{w:'Threat Sensitivity',t:'These two are near-opposites and make the sharpest inner tension and the best partnerships. Approach opens; vigilance checks.'},{w:'Behavioral Regulation',t:'High approach with developing regulation is the classic bold child. Grow the pause; keep the boldness.'}]},

{id:'kindler', n:'06', name:'Positive Affect & Pleasure', trait:'Positive Affect & Pleasure', region:1, color:'#7A8F3E',
 poles:['Quiet, inward delight','Bright, visible joy'],
 metaphor:{name:'The Rising Sun', text:'For the openly joyful, joy rises like the sun, early, warm, and plain to see. For the more restrained, delight is real but quieter, a lamp in a window rather than a sky on fire. Quiet enjoyment is not absent gratitude.'},
 cq:'Is there something here to delight in, and may I show it?',
 desc:'How readily a person experiences, anticipates, and shows enjoyment. This is a system of its own, not merely the absence of sadness.',
 high:['Enjoyment arises readily and openly','Anticipates good things with eagerness','Recovers through enjoyable engagement','Seeks frequent positive activation'],
 low:['Enjoyment is quieter, less visible','Delight needs specific conditions','Expression may understate real feeling','Finds pleasure in calm, small moments'],
 gifts:[{t:'Contagious warmth',d:'The openly joyful person lifts a room; enthusiasm is a gift that gathers people.'},{t:'Hope',d:'A ready capacity for delight fuels resilience and the anticipation that keeps going.'},{t:'Depth over display',d:'The restrained person often feels deeply while showing little, and means every word they do express.'},{t:'Savoring',d:'Quiet delight tends to notice small, calm goods that louder joy rushes past.'}],
 edges:[{t:'Joy mistaken for shallowness',d:"The openly joyful person's brightness can be misread as not taking things seriously."},{t:'The cheerful mask',d:'Outward warmth can hide a struggle no one thinks to check on.'},{t:'Coolness misread as unhappiness',d:'The restrained person is not sad; they simply show less.'}],
 confuse:['superficiality','naivety','insincerity','realism, in the restrained'],
 fit:'Include both calm and high-energy sources of pleasure. Do not require emotional performance from the restrained.',
 scaffold:'Proactively check on the outwardly cheerful. Help the restrained find words for delight they feel but rarely show.',
 stretch:"Develop the capacity to notice, receive, express, and share appropriate joy, whatever one's natural volume.",
 formation:'The openly joyful learn that joy is not frivolous but load-bearing, a strength to be shared and, when it masks pain, to be honest about. The restrained learn that letting delight show is a gift to others, not a loss of dignity.',
 virtue:'Gratitude, joy', verse:'The joy of the Lord is your strength. (Nehemiah 8:10)',
 concert:[{w:'Affiliation & Social Reward',t:'High joy plus high affiliation makes a natural gatherer, the warmth others orbit toward.'},{w:'Sadness & Loss Sensitivity',t:'A person can run high on both delight and sorrow, feeling the whole range vividly. This is depth, not instability.'}]},

{id:'kindred', n:'07', name:'Affiliation & Social Reward', trait:'Affiliation & Social Reward', region:1, color:'#5C6B2F',
 poles:['Rewarded by solitude','Rewarded by closeness'],
 metaphor:{name:'The Hearth', text:'The connection-seeker draws life from the shared fire and feels the cold when far from one. The more independent person carries their own warmth and needs solitude to keep it. Neither the need for others nor the need for self is a virtue or a flaw.'},
 cq:'Am I close to my people, and are they close to me?',
 desc:'How strongly a person seeks, enjoys, and sustains closeness and companionship. This is not the same as kindness, empathy, or social skill.',
 high:['Seeks shared experience often','Finds relationships strongly rewarding','Processes by talking things through','Sensitive to distance and exclusion'],
 low:['Needs more solitude to feel settled','Finds connection rewarding in smaller doses','Processes internally before sharing','Feels heavy social demand as intrusion'],
 gifts:[{t:'Bond-building',d:'The connection-seeker forms and tends relationships, and often holds a group together.'},{t:'Warmth and loyalty',d:'Closeness deeply valued tends to be closeness deeply given.'},{t:'Self-possession',d:'The independent person is comfortable alone, thinks for themselves, and does not need the room to agree.'},{t:'Depth over breadth',d:'Fewer, less frequent connections are often richer and more considered.'}],
 edges:[{t:'Closeness that can smother',d:"The connection-seeker may read another's need for space as rejection."},{t:'Fear of the empty room',d:'Solitude can be genuinely hard for the connection-seeker to bear.'},{t:'Distance mistaken for coldness',d:"The independent person's need for space is easily read as not caring."}],
 confuse:['empathy','agreeableness','kindness','attachment security','social skill'],
 fit:'Respect the real need for both connection and solitude. Do not treat sociability as moral superiority.',
 scaffold:'Give the connection-seeker structured ways in; give the independent person permission and warm scripts for closeness and boundaries.',
 stretch:'For high affiliation, build comfort with solitude and boundaries. For low, practice intentional connection and reciprocity.',
 formation:'The connection-seeker learns that love includes letting others have space, and that solitude is not abandonment. The independent learn that self-possession is completed, not compromised, by intentional communion. Both learn the same lesson from opposite doors: to give and receive closeness in freedom.',
 virtue:'Love, communion held with healthy boundaries', verse:'It is not good for the man to be alone. (Genesis 2:18), with: look also to the interests of others. (Philippians 2:4)',
 concert:[{w:'Sadness & Loss Sensitivity',t:'High affiliation with high loss sensitivity produces strong attachment and sharp pain after conflict or exclusion. Repair matters enormously.'},{w:'Frustration & Anger',t:'When the connection-seeker also runs hot with frustration, closeness and conflict tangle; the same intensity that bonds can wound.'}]},

{id:'sentinel', n:'08', name:'Threat Sensitivity', trait:'Threat Sensitivity', region:2, color:'#5E3A5E',
 poles:['Slow to alarm','Quick to vigilance'],
 metaphor:{name:'The Watchtower', text:"The vigilant stand watch so the community is not caught off guard. That vigilance is a gift when the danger is real and a burden when the alarm keeps ringing after the threat has passed. The tower's strength is also its temptation: to see peril everywhere."},
 cq:'Is this safe, and can I be sure before I commit?',
 desc:'How readily uncertainty, novelty, evaluation, or possible danger activates caution, hesitation, or withdrawal. An easily-alerted alarm, protective when well-calibrated.',
 high:['Notices possible risk quickly','Pauses, observes, or seeks reassurance','Can be captured by what might go wrong','Stays wary even after safety is shown'],
 low:['Needs clearer danger to grow concerned','Enters uncertain situations readily','Stays calm under pressure','May overlook genuine warning signs'],
 gifts:[{t:'Foresight',d:'The vigilant person sees the risk others miss and prevents trouble before it starts.'},{t:'Conscientiousness',d:'Care about what could go wrong often produces thoroughness and reliability.'},{t:'Steadiness under fire',d:'The low-threat person keeps their head where others panic and moves where others freeze.'},{t:'Calm in the unknown',d:'Less alarm means more freedom to enter uncertainty and act.'}],
 edges:[{t:'Alarm that outlives the danger',d:'The vigilant person can stay braced long after the threat is gone.'},{t:'Avoidance that narrows life',d:'Escaped uncertainty, repeatedly, can shrink the world.'},{t:'Blind spots',d:'The low-threat person may walk past warnings that deserved a pause.'}],
 confuse:['an anxiety disorder','shyness','weakness','low affiliation'],
 fit:'Prepare without catastrophizing. Permit observation; do not reinforce every escape from manageable uncertainty.',
 scaffold:'Offer graduated, supported exposure and honest reassurance. Teach accurate risk appraisal, not blanket comfort.',
 stretch:'Act according to reality and values rather than automatic alarm. For the low-threat, take real danger seriously.',
 formation:'The vigilant are not called to stop watching. They are called to learn which alarms to trust. Vigilance surrendered to love becomes wisdom: the watchtower that protects without imprisoning. The path is not fearlessness but faith large enough to act while the alarm still sounds.',
 virtue:'Courage, discernment', verse:'There is no fear in love, but perfect love casts out fear. (1 John 4:18)',
 concert:[{w:'Novelty & Reward Approach',t:'Vigilance and approach are the two halves of good judgment. Alone, one freezes and one leaps; together they weigh, then move.'},{w:'Sadness & Loss Sensitivity',t:'High threat plus high sadness produces a tender, careful soul who needs proactive warmth and gentle exposure, not toughening.'}]},

{id:'forge', n:'09', name:'Frustration & Anger', trait:'Frustration & Anger', region:2, color:'#7A3A4E',
 poles:['Slow to kindle','Quick to protest'],
 metaphor:{name:'The Forge-Fire', text:'Blocked energy, like metal in a forge, can be beaten into something useful or can simply burn. The heat is not the problem. What the heat is turned toward is everything. The same fire that forges a tool can scorch a hand.'},
 cq:'What is standing in my way, and why will no one move it?',
 desc:'How readily a blocked goal, a restraint, an interruption, or a violated expectation activates anger and protest. Anger here is energy mobilized against an obstacle, not aggression itself.',
 high:['Frustration activates quickly','Protest is strong or visible','Anger mobilizes forceful action','Interruption feels highly disruptive'],
 low:['Needs more obstruction to activate','Protest is mild or internal','Tolerates delay and restraint more easily','May under-communicate a real boundary'],
 gifts:[{t:'Drive against obstacles',d:'The quick-to-heat person does not accept a blocked path quietly; it pushes, and things move.'},{t:'A sense of justice',d:'Quick anger at wrong can be the engine of advocacy and courage.'},{t:'Forbearance',d:'The slow-to-heat person absorbs friction, tolerates delay, and keeps the peace.'},{t:'Even temper',d:'Slow to anger often means steady, hard to rattle, safe to be near.'}],
 edges:[{t:'Heat that harms',d:'Fast, forceful protest can wound before it is aimed.'},{t:'The long grudge',d:'Slow relational recovery can outlast the moment that caused it.'},{t:'The unspoken boundary',d:'The slow-to-heat person may swallow a real limit until it curdles into withdrawal.'}],
 confuse:['aggression','hostility','defiance','passion','cruelty'],
 fit:'Validate the signal without endorsing harm. Name the blocked goal; give protest a legitimate channel.',
 scaffold:'Offer one rehearsed sentence for the heat: I need a minute, I am frustrated. Wait for real recovery before problem-solving.',
 stretch:'For the quick-to-heat, practice proportion, perspective, and repair. For low, name a boundary before it becomes resentment.',
 formation:'This heat is not asked to go cold. It is asked to aim. Anger is a signal that something is wrong, and a person who can feel that heat, hold it, and turn it toward repair rather than harm carries one of the most useful and most dangerous gifts there is. Formation is the anvil where heat becomes a tool.',
 virtue:'Righteous anger disciplined into gentleness', verse:'Be angry and do not sin; do not let the sun go down on your anger. (Ephesians 4:26)',
 concert:[{w:'Behavioral Regulation',t:'Fast frustration with a strong pause becomes force under control; without the pause, the heat leads.'},{w:'Affiliation & Social Reward',t:'When that heat burns near the people a person loves most, closeness and conflict entangle. Repair is the whole work.'}]},

{id:'tender', n:'10', name:'Sadness & Loss Sensitivity', trait:'Sadness & Loss Sensitivity', region:2, color:'#4C3660',
 poles:['Recovers quickly','Feels loss deeply'],
 metaphor:{name:'The Deep Well', text:"Some souls hold sorrow the way a deep well holds water, quietly, and for a long time. That depth is where compassion is drawn from. The danger is not the depth but drawing so much that the person goes under. The gift is water for others' thirst."},
 cq:'Something is lost. Will anyone sit with me in it?',
 desc:'How readily loss, separation, exclusion, disappointment, or helplessness activates sadness and a drop in energy. This is not depression, pessimism, or weakness.',
 high:['Loss registers strongly and lingers','Needs time to process endings','Responds deeply to separation','Energy drops noticeably after loss'],
 low:['Recovers readily from many disappointments','Shifts quickly toward alternatives','Less visibly affected by many losses','May move on before others are ready'],
 gifts:[{t:'Compassion',d:"The deep feeler knows sorrow from the inside and can sit with another's grief without flinching."},{t:'Depth and loyalty',d:'Feeling loss deeply is the shadow side of loving deeply.'},{t:'Resilience',d:'The low-sadness person bounces back, keeps momentum, and helps others do the same.'},{t:'Perspective',d:'Quick recovery can offer a steadying, this-too-shall-pass presence in hard seasons.'}],
 edges:[{t:'Sinking under the weight',d:'The deep feeler can be immobilized by a sorrow they cannot yet set down.'},{t:'Grief that isolates',d:'Deep feeling, unaccompanied, can turn inward and hide.'},{t:'Moving on too fast',d:"The low-sadness person may bypass a grief that deserved to be felt, their own or another's."}],
 confuse:['depression','pessimism','emotional depth','weakness','being dramatic'],
 fit:'Acknowledge the loss beneath the emotion. Permit sadness without rushing to eliminate it.',
 scaffold:'Support expression through words, movement, art, relationship, or prayer. Stay present rather than fixing.',
 stretch:'For the deep feeler, carry sorrow without being immobilized. For the low-sadness, stay present to grief without bypassing it.',
 formation:'The deep feeler learns that sorrow, accompanied, becomes compassion, and that the well is meant to water others, not to drown the one who holds it. The quick-to-recover learn to slow down at the graveside, their own and others\u2019, long enough to let grief do its honest work.',
 virtue:'Compassion, hope', verse:'Blessed are those who mourn, for they shall be comforted. (Matthew 5:4)',
 concert:[{w:'Sensory Sensitivity',t:'High sensitivity feeding high sadness makes a soul who feels everything and needs help carrying it. Protect and accompany.'},{w:'Affiliation & Social Reward',t:'Deep loss sensitivity plus strong affiliation means exclusion and conflict cut deep. Repair and reassurance are essential.'}]},

{id:'lightning', n:'11', name:'Attentional Capture', trait:'Attentional Capture', region:3, color:'#2E7D84',
 poles:['Hard to divert','Easily drawn'],
 metaphor:{name:'The Weathervane', text:'A weathervane turns to whatever wind is strongest. That responsiveness is why the easily drawn mind notices what everyone else misses, and why holding a single course against a strong pull is genuinely hard. The instrument that catches every current is not broken. It is sensitive.'},
 cq:'What is the most compelling thing here, and can I keep from turning to it?',
 desc:'How readily attention is automatically pulled toward what is new, intense, emotional, or meaningful, before any deliberate choice is made. The precise version of the old idea of distractibility.',
 high:['Notices changes and interruptions readily','Detects what others miss','Attention is pulled toward the salient','Struggles to protect a goal from interruption'],
 low:['Stays absorbed despite surrounding activity','Sustains focus in busy settings','May miss instructions, cues, or changes','Hard to interrupt or redirect once locked in'],
 gifts:[{t:'Wide awareness',d:'The easily drawn mind takes in the whole field and catches the detail, the change, the danger, the opportunity.'},{t:'Creative association',d:'A mind open to every current makes unexpected connections.'},{t:'Deep absorption',d:'The low-capture person can disappear into a task and stay there, undistracted, for hours.'},{t:'Immovable focus',d:'Hard to interrupt can mean hard to derail, a real strength in a noisy world.'}],
 edges:[{t:'The protected goal that slips',d:'The easily drawn mind loses the thread when a stronger signal pulls.'},{t:'Interruption that costs',d:'Every diversion has a re-entry price the easily drawn mind pays repeatedly.'},{t:'Missed cues',d:'The low-capture person, deeply absorbed, may not hear the instruction or notice the change.'}],
 confuse:['intentional focus','ADHD','curiosity','low persistence','perceptual sensitivity'],
 fit:'Reduce irrelevant interruption for the easily drawn; give the deeply absorbed clear transition signals.',
 scaffold:'Teach a capture plan: when interrupted, write the next step before turning away, so re-entry is cheap.',
 stretch:'For high capture, protect a chosen goal and disengage from irrelevant pulls. For low capture, monitor the field and redirect when needed.',
 formation:'The easily drawn mind learns that attention is the one power we most truly own, and the one most easily stolen. To notice everything and still choose where to stand is a discipline, not a defect, and it is learned slowly, with structure and grace. What we attend to, we become.',
 virtue:'Recollection, the discipline of attention', verse:'Set your minds on things above. (Colossians 3:2)',
 concert:[{w:'Effortful Attentional Control',t:'Capture is the pull; effortful control is the counterweight. One person can have a strong pull and a strong hand, or a strong pull and a developing one.'},{w:'Motor Activity',t:'High capture plus high motion reads as chaos, and is often a nervous system built for input, needing structure rather than correction.'}]},

{id:'lantern', n:'12', name:'Effortful Attentional Control', trait:'Effortful Attentional Control', region:3, color:'#2A6B72',
 poles:['Structure-dependent','Self-directed focus'],
 metaphor:{name:'The Lantern', text:'Attention is a lantern; wherever it shines, the world becomes clear, and everything else falls into shadow. The work is holding the light steady on what matters, and turning it deliberately when the moment calls. The skill is not brightness. It is aim.'},
 cq:'Can I put my attention where it needs to be, and move it when it must?',
 desc:'How well a person can intentionally place, sustain, release, and redirect attention. Unlike raw reactivity, this capacity grows.',
 high:['Focuses intentionally, even on the dull','Returns to task after interruption','Shifts smoothly when priorities change','Uses goals to organize attention'],
 low:['Depends on external structure to focus','Loses the task after an interruption','Gets stuck, or shifts too readily','Attention follows immediate interest'],
 gifts:[{t:'Directed focus',d:'Strong control holds attention on what matters and sees hard things through.'},{t:'Flexible agency',d:'Strong shifting means moving between tasks and perspectives without being trapped in one.'},{t:'Honest dependence',d:'The person whose control is still growing teaches everyone that attention is built with scaffolding, not shamed into place.'},{t:'Immersion',d:'Strong focus, even where shifting lags, produces deep and sustained work.'}],
 edges:[{t:'The stuck light',d:'Strong focus with weak shifting fixes on one thing past the point of use.'},{t:'The wandering light',d:'Weak focus lets the goal dissolve after every interruption.'},{t:'Structure mistaken for weakness',d:'Needing external supports to focus is a stage of growth, not a character flaw.'}],
 confuse:['intelligence','obedience','motivation alone','attentional capture'],
 fit:'Make goals visible. Break work into meaningful units. Match task length to current capacity and expand it gradually.',
 scaffold:'Use written restart points and transition routines. Externalize the structure the attention cannot yet hold alone.',
 stretch:'Develop flexible agency over attention, not merely longer concentration: place it, hold it, release it, move it on purpose.',
 formation:'Here a person learns that a life is largely built from what it repeatedly attends to. To aim the light on purpose, toward the true, the good, and the necessary, is among the most consequential freedoms a person can develop, and it is developed patiently, over years.',
 virtue:'Self-mastery, single-heartedness', verse:'Your word is a lamp to my feet and a light to my path. (Psalm 119:105)',
 concert:[{w:'Attentional Capture',t:'The pull and the hand. Strong control tames strong capture into vivid, usable attention; weak control leaves it scattered.'},{w:'Behavioral Regulation',t:'Attention placed and behavior governed are the two arms of self-regulation, and they grow together.'}]},

{id:'steward', n:'13', name:'Behavioral Regulation', trait:'Behavioral Regulation', region:3, color:'#1F5257',
 poles:['Impulse-led','Purpose-governed'],
 metaphor:{name:'The Helm', text:'Behavioral regulation is the hand on the rudder, holding a course against wind, current, and impulse. The point is not rigidity; a good helm also knows when to change course. Freedom here is not doing whatever the moment wants. It is being able to do what the whole life needs.'},
 cq:'Can I do what matters, even when everything in me wants otherwise?',
 desc:'How well behavior can organize around a chosen goal when impulse, reluctance, boredom, or immediate reward competes with it. This is not compliance, and not moral worth.',
 high:['Pauses before acting on impulse','Begins necessary but un-preferred tasks','Persists through manageable difficulty','Revises a goal when the evidence changes'],
 low:['Acts on the strongest immediate impulse','Knows what to do but struggles to begin','Disengages when reward is delayed','Persists rigidly, or quits too soon'],
 gifts:[{t:'Responsible freedom',d:'Strong regulation can subordinate the immediate to the important, the mark of a life that is genuinely self-governed.'},{t:'Perseverance',d:'The capacity to continue through the dull, hard middle is where most good things are actually made.'},{t:'Spontaneity',d:'The lower-regulation person often brings freshness, responsiveness, and willingness that over-control can lose.'},{t:'Honest limits',d:'Struggling to begin or to stop reveals, plainly, where scaffolding is still needed.'}],
 edges:[{t:'Impulse ahead of intention',d:'Low inhibitory control acts before the goal can organize behavior.'},{t:'The task that will not start',d:'Weak activation control knows exactly what to do and still cannot begin.'},{t:'Rigid persistence',d:'Regulation can harden into pushing on with an unwise course long past the moment to stop.'}],
 confuse:['compliance','obedience','virtue itself','intelligence','productivity','moral worth'],
 fit:'Reduce the size of the first step. Use visible sequences. Distinguish inability, overload, disagreement, avoidance, and defiance before responding.',
 scaffold:'Build implementation intentions: when X happens, I will do Y. Reinforce recovery and re-entry after failure, not only success.',
 stretch:'Grow responsible freedom: to inhibit, initiate, persist, revise, and stop according to reality, values, and long purposes.',
 formation:'This is the dimension where temperament most clearly becomes character. Every pause practiced, every hard beginning made, every wise stop chosen lays down the habit from which a self-governed life is built. This is not about becoming controllable. It is about becoming free: able, at last, to do the good one actually intends.',
 virtue:'Self-control, the fruit of a governed life', verse:'A fruit of the Spirit is self-control. (Galatians 5:22-23)',
 concert:[{w:'Novelty & Reward Approach',t:'Bold approach with developing regulation is the classic spirited child. The plan is never to dim the boldness, only to grow the brakes.'},{w:'Frustration & Anger',t:'Fast frustration governed by strong regulation becomes force under control. The same heat, without the helm, simply leads.'}]}
];

export const CONSTELLATIONS = [
{id:'wildfire', n:'01', name:'The Wildfire', recipe:{engine:1, dynamo:1, pioneer:1, sentinel:-1, steward:-1},
 mix:'High Engine · High Dynamo · High Pioneer · Low Sentinel · developing Steward',
 desc:'Boundless, bold, joyful forward motion that can outrun its own judgment. This is the child on top of the furniture and the adult three ventures deep. Magnetic, exhausting, and never boring.',
 asks:'How fast can we go, and what else is there to try?',
 image:'A grass fire in a dry wind: magnificent, fast, and desperately in need of a firebreak.',
 needs:'Grow the brakes, never dim the fire. Pause cues, consequence-naming, and rehearsal outside the heated moment.'},
{id:'deepcurrent', n:'02', name:'The Deep Current', recipe:{attuned:1, tender:1, kindred:1},
 mix:'High Attuned · High Tender · slow recovery · High Kindred',
 desc:'A person who feels the world and its people with unusual depth, and who tires under the weight of it. The one who cries at the film everyone else shrugged off, and who remembers the unkind word for a week.',
 asks:'Who will help me carry what I feel?',
 image:'A deep, slow river: rich and life-giving, and easily troubled by a storm far upstream.',
 needs:'Protection and accompaniment, not toughening. Real recovery time, and a hand to help carry the weight.'},
{id:'scholar', n:'03', name:'The Sentinel Scholar', recipe:{pioneer:-1, sentinel:1, lantern:1, lightning:-1},
 mix:'Low Pioneer · High Sentinel · strong focus · low shifting',
 desc:'The careful specialist who masters a domain in depth and mistrusts the untested. Slow to enter, hard to move once settled, and often the most knowledgeable person in the room.',
 asks:'Is it proven, and may I go deep rather than wide?',
 image:'An old library: deep, ordered, and slow to admit a new book to the shelf.',
 needs:'Flexible transitions and graded entry, not forced extraversion. Honor the depth; widen the door slowly.'},
{id:'standard', n:'04', name:'The Standard-Bearer', recipe:{forge:1, kindred:1},
 mix:'High Forge · High Kindred · strong persistence · slow relational recovery',
 desc:'The passionate advocate who fights for people and takes conflict personally. The one who will not let an injustice pass, and who is wounded by the very battles they choose.',
 asks:'This is wrong for us. Why will no one else stand up?',
 image:'A banner carried into the wind: seen from far off, and frayed by every gust.',
 needs:'Proportion, perspective-taking, and above all, repair. The cause is served by the relationship, not against it.'},
{id:'stillwater', n:'05', name:'The Still Water', recipe:{engine:-1, dynamo:-1, steward:1},
 mix:'Low Engine · Low Dynamo · strong Steward · balanced elsewhere',
 desc:'The steady anchor whose calm holds a room together. Rarely the loudest voice, often the one others steady themselves against without knowing they are doing it.',
 asks:'What is the wise, unhurried next step?',
 image:'A deep, still pond: unremarkable on the surface, and steadying to everyone who sits beside it.',
 needs:'To be seen and drawn out. Steadiness is not absence, and quiet is not indifference.'},
{id:'ember', n:'06', name:'The Quiet Ember', recipe:{kindler:-1, tender:1, sentinel:1, steward:-1},
 mix:'Low outward intensity · High Tender · High Sentinel · low activation control',
 desc:'The child or adult who struggles hard and shows little, and is therefore easy to overlook. The one who is fine, always fine, until suddenly they are not.',
 asks:'Will anyone notice that I am not okay?',
 image:'An ember under ash: real heat, and almost no visible flame.',
 needs:'Proactive check-ins and help with initiation. Do not wait for a visible crisis to look closer.'},
{id:'firstlight', n:'07', name:'The Firstlight', recipe:{kindler:1, pioneer:1, kindred:1, sentinel:-1},
 mix:'High Kindler · High Pioneer · High Kindred · Low Sentinel',
 desc:'The radiant connector who lights up a room and opens every door. Warm, quick, and generous, the one everyone is glad to see arrive.',
 asks:'Who is here, and what good thing can we do together?',
 image:'A sunrise over a harbor: warm, welcoming, and easy to follow out to sea.',
 needs:'To learn that not every silence is rejection, and that some doors are worth studying before walking through.'},
{id:'weathervane', n:'08', name:'The Weathervane', recipe:{lightning:1, dynamo:1, lantern:-1},
 mix:'High Lightning Rod · High Dynamo · developing Lantern-Bearer',
 desc:'The vivid, associative, everywhere-at-once mind, often deeply creative and easily scattered. A dozen ideas an hour, and a desk full of open loops.',
 asks:'What is the most interesting thing in the room right now?',
 image:'A weathervane in a gusting wind: catching every current, and hard to hold on a single bearing.',
 needs:'External structure and capture plans, never shame. The gift is real; the scaffolding is the work.'},
{id:'anchorhold', n:'09', name:'The Anchorhold', recipe:{sentinel:1, steward:1, pioneer:-1},
 mix:'High Sentinel · strong Steward · Low Pioneer',
 desc:'The careful guardian who keeps a system safe and thinks before every move. The one who reads the whole contract, checks the exits, and is quietly right more often than anyone admits.',
 asks:'What could go wrong, and how do we prevent it?',
 image:'A harbor wall: unglamorous, and the reason the boats are still there after the storm.',
 needs:'Graded courage: small, supported steps into the uncertainty they would otherwise avoid.'},
{id:'forgeheart', n:'10', name:'The Forge-Heart', recipe:{forge:1, pioneer:1, steward:1},
 mix:'High Forge · High Pioneer · strong persistence',
 desc:'The driven changemaker who sees what is broken and will not stop until it moves. The one who starts the hard thing, pushes through the resistance, and reshapes what they touch.',
 asks:'What needs to change, and why are we still waiting?',
 image:'A hammer meeting an anvil: relentless, reshaping, and loud.',
 needs:'Patience with process and people, and the underrated wisdom of strategic disengagement.'},
{id:'lanternfog', n:'11', name:'The Lantern in the Fog', recipe:{attuned:1, lantern:1, sentinel:1},
 mix:'High Attuned · strong Lantern-Bearer · High Sentinel',
 desc:'The attuned regulator who feels a great deal, watches carefully, and holds it all with unusual control. Calm on the outside, working hard on the inside.',
 asks:'How do I stay clear and steady in all of this?',
 image:'A lighthouse in fog: feeling every shift in the weather, and holding the beam steady anyway.',
 needs:'Permission to lower the guard in safe places, and genuine recovery from the labor of holding steady.'},
{id:'openfield', n:'12', name:'The Open Field', recipe:{pioneer:1, kindred:1, attuned:-1, kindler:1},
 mix:'High Pioneer · High Kindred · Low Attuned · High Kindler',
 desc:'The easy-going, resilient, come-what-may temperament that the older maps called the easy child. Adaptable, warm, and hard to rattle.',
 asks:"Isn't this good? Let's enjoy it.",
 image:'An open meadow under a mild sky: few obstacles, and easy to cross.',
 needs:'To slow down enough to notice what does not announce itself, in themselves and in the people around them.'}
];
